### ISSUE TITLE
Create GraphQL server starter

### ISSUE THREAD

**Issue by blakek** [gsandf/dev-scripts#9]
Create a server that does all GraphQL server setup.

Proposed usage:

```js
import { createRootSchema, graphqlServer } from '@gsandf/graphql-server';
import express from 'express';

const app = express();

app.use('/graphql', graphqlServer(req => ({
  context: { user: req.user }, // example of setting context
  playground: '/graphiql', // route to playground; disabled if falsy
  schema: createRootSchema([ ...typesAndResolvers ]), // GraphQL executable schema
  visualization: '/voyager' // route to voyager; disabled if falsy
})))

app.use('/whatever', () => {
  console.log("do what you want! it's a normal express server.")
})
```

**Comment by blakek** [comment]
After looking into [`graphql-yoga`](https://github.com/prismagraphql/graphql-yoga), this proposal is _really close_ to what the Prisma team has created.  The only difference is this proposal is an express middleware where `graphql-yoga` wraps express and exposes a method for adding middleware.

We could consider using that project, adding it to a list of project starters, and closing this issue.

**Comment by zstickles-gsandf** [comment]
I've been learning the GrpahQL DSL by using graphql-yoga and I really appreciate how easy it makes everything. It's also what the "official" tutorial suggests.

**Comment by zanchi** [comment]
One thing I see a potential issue with is that you have to specify special _GraphQL_ middlewares? Maybe I'm reading the docs wrong but it looks like you can't just use any old middleware
